import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import FixSession from "./FixSession";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FixSession session={session}>
          {/* <div>

          <Navbar />

          {children}
          </div> */}
          <div className="grid grid-cols-10 min-h-screen">
            {/* Sidebar (Navbar) - 30% width */}
            <div className="col-span-2 bg-gray-800 text-white p-4">
              <Navbar />
            </div>

            {/* Main Content (Children) - 70% width */}
            <div className="col-span-8 p-4">{children}</div>
          </div>
        </FixSession>
      </body>
    </html>
  );
}
